nanvix/nanvix

- include/nanvix/pm.h
- include/nanvix/syscall.h
- include/unistd.h
- src/kernel/pm/pm.c
- src/kernel/pm/sched.c
- src/kernel/sys/clear.c
- src/kernel/sys/execve.c
- src/kernel/sys/gticks.c
- src/kernel/sys/ps.c
- src/kernel/sys/syscalls.c
- src/lib/libc/unistd/clear.c
- src/lib/libc/unistd/gticks.c
- src/lib/libc/unistd/ps.c
- src/ubin/clear/clear.c
- src/ubin/makefile
- src/ubin/nim/nim.c
- src/ubin/ps/ps.c
It was inserted into the Nanvix:
3 syscalls:
- sys_clear: clear the screen
- sys_ps: gets the process state
- sys_gticks: get the system ticks since from initialization
3 programs:
- ps: same idea of the linux command, but much simpler.
- clear: clear the actual tty
- nim: the Nim game
A simple process priority correction, as we talked a few days ago.
*Sorry for the so long pull :/
> Syscalls, programs and more

- src/sbin/test/test.c
SEM_CREATE fixed, I also took the freedom of placing in the pull the correction of the loop and the erroneous destruction of the semaphores.
> bug fix: wrong attribution in SEM_CREATE

- tools/dev/setup-bochs.sh
- tools/dev/setup-toolchain.sh
Updated GCC cross-compiler to 5.3.0 and bochs VM to 2.6.8.
> Updated gcc and bochs VM

- src/ubin/tsh/main.c
- src/ubin/tsh/tsh.h
Stack based implementation of TSH command history.
> TSH command history

- CREDITS
> Updated CREDITS

- src/kernel/dev/dev.c
- src/kernel/pm/pm.c
Moved clock & FPU initialization as part of device initialization.
> init reorganization

- src/kernel/mm/region.c
With this, I believe which fixes the previous problem for overlapping regions.
> Checking for overlapping regions

- include/nanvix/clock.h
- include/nanvix/syscall.h
- src/kernel/arch/x86/cmos.c
- src/kernel/sys/syscalls.c
- src/kernel/sys/time.c
- src/ubin/tsh/tsh.h
Time system call implementation - initial draft.
> Time syscall

- include/locale.h
- src/lib/libc/locale/locale.c
Locale is very close to the ISO C, I just gave some improvement, in according to #78
> ISO C - Locale

- src/kernel/mm/region.c
This pull fixes the issue presented on #96, the problem occurs due to trying to use a new page table without allocate any kernel pages for that. This also occurs in the dev branch.
> bug fix: demand fill on a present page

- CREDITS
- tools/build/build-img.sh
Basically the same things changed in the master branch were changed here.
> Add Credits and update build-img.sh

- .gitignore
- include/nanvix/debug.h
- include/nanvix/mboot.h
- src/kernel/arch/x86/boot.S
- src/kernel/debug/debug.c
- src/kernel/init/main.c
- src/kernel/makefile
- tools/img/menu.lst
- Add a menu entry to enter in debug mode by passing a parameter on the stack then to kmain
- kmain handles the parameter and call dbg-init(), which is only a kprintf() for the moment.
> Early debug features

- include/limits.h
- include/sys/sem.h
- src/kernel/pm/pm.c
- src/kernel/sys/semclose.c
- src/kernel/sys/semopen.c
- src/kernel/sys/sempost.c
- src/kernel/sys/semunlink.c
- src/lib/libc/sys/sem/semclose.c
- src/lib/libc/sys/sem/semopen.c
- src/lib/libc/sys/sem/semunlink.c
- src/sbin/test/test.c
Handling multiple sem_open/sem_close thanks to the addition of a pid table into the ksem structure.
Also improving coding style.
> Handling multiple sem_open/sem_close

- CREDITS
CREDITS update as requested by Pedro Penna.
> CREDITS update

- tools/dev/setup-bochs.sh
This pull request updates the Bochs version in setup-bocks.sh.
> Bochs updated.

- .travis.yml
- Dockerfile.tvci
Dockerfile will be priority one, and Dockerfile.tvci will be the one triggered by Travis-CI
> Fixed Travis-CI: Resolving conflicts between Dockerfiles

- include/nanvix/pm.h
- src/kernel/arch/x86/clock.c
- src/kernel/arch/x86/exception.c
- src/kernel/mm/mm.c
- src/kernel/mm/paging.c
- src/kernel/sys/fork.c
Bug fix for issue https://github.com/nanvix/nanvix/issues/139.
> fix KERNEL_WAS_RUNNING macro

- src/kernel/pm/die.c
That solution was proposed by @Theldus on Gitter and work really fine to fix #173.
> Fix wait() waiting indefinitely on multiple child processes - fixes #173

- src/lib/libc/stdio/stdio.c
> Fix problem with buffer and printing on multi process programs

- src/kernel/mm/mm.c
- src/kernel/sys/fork.c
- src/sbin/test/test.c
Fix for issue https://github.com/nanvix/nanvix/issues/139.
> Fixing Bad intlvl on fork()

- src/kernel/arch/x86/utilities.S
https://github.com/nanvix/nanvix/issues/184
> Issue 184 Bug Fix

- src/kernel/arch/x86/utilities.S
https://github.com/nanvix/nanvix/issues/185
> Issue 185 Bug Fix

- src/kernel/arch/x86/utilities.S
https://github.com/nanvix/nanvix/issues/186
> Issue 186 Bug Fix

- src/kernel/mm/paging.c
https://github.com/nanvix/nanvix/issues/188
> Issue 188 Bug Fix

- tools/dev/setup-qemu.sh
> Upating QEMU to Version 2.12.0

- src/kernel/arch/i386/hooks.S
- src/kernel/arch/i386/utilities.S
This PR fixes building issues in the i386 arch and conforms to the threads implementation.
> Conforming low-level i386 functions to the threads branch

- README.md
- src/kernel/pm/sched.c
Updated the scheduling algorithm to consider other fields than counter (priority and nice):
- Added a macro to calculate the process' effective priority (priority + nice - counter).
- Added a macro to verify whether or not we should update the next process to be executed.
> Priority Scheduler

- src/sbin/test/test.c
- tools/build/build-img.sh
**Changes**
* `build-img`: modified *format* function to do not create hdd special file.
* `test.c`: modified *work_io* function to read from ramdisk instead of hdd.
> Hotfix unexpected hdd

- CREDITS
> Updates credits with my references

- docker/ubuntu/Dockerfile
- docker/ubuntu/README.md
* Dockerfile to create a container with Nanvix
* Dockerfile to create an Ubuntu container that runs Nanvix in the QEMU emulator upon starting a bash session! 
* The goal is to facilitate installation and avoid cluttering the host machine with installations.
* Tested implementation.
> Nanvix Dockerized Support

- docker/ubuntu/Dockerfile
* Fix warning generated by QEMU about a deprecated flag used!
* Change tested
> [Fix] Replace deprecated qemu flag with the new one
