nanvix/nanvix

include/dev/tty.h
include/termios.h
src/kernel/dev/tty/keyboard.c
src/kernel/dev/tty/tty.c
src/lib/libc/termios/tcsetattr.c
src/ubin/tsh/main.c
src/ubin/tsh/tsh.h

The main purpose of this pull is to add the ability to 'command stack' in TSH application, for this a few changes to the system and program were needed:
System:
- tcsetattr() implemented.
- very few bug correction.
- recognize keyup and keydown in raw mode.
Program:
- tsh now works in raw mode and it was necessary to 'rewrite' the canonical behavior in it.
- identification of keys: keyup/keydown and basic manipulation of a circular stack.

Command stack in TSH

---

include/i386/fpu.h
include/nanvix/pm.h
src/kernel/arch/x86/fpu.c
src/kernel/arch/x86/utilities.S
src/kernel/pm/pm.c
src/kernel/sys/fork.c
src/sbin/test/test.c

Support floating point unit (x87 coprocessor) was added, and its registers, control words, instruction pointers... is saved every context switch in the system.

Support for floating-point unit.

---

include/nanvix/region.h
src/kernel/mm/region.c

With this pull, the maximum size of a region is dynamically defined as the region grows or shrinks.
Thus, it can be avoided in future implementations that the kernel be in doubt which region belongs to a particular address.

Implementing max size in region

---

src/kernel/arch/x86/cmos.c

Fixes the following - 
1. Serious bug in startup time. Reading CMOS register 0x09 returns only the last 2 digits of current year. We need to add this value to the right offset (CURR_MILLENNIUM) to get the actual year.
2. Minor conformance (80 column rule, space before and after binary operators) to coding rules as described in $NANVIX_HOME/doc/coding_style.

Bug fix for millennium adjustment for year value

---

include/nanvix/clock.h
include/time.h
src/lib/libc/makefile
src/lib/libc/time/time.c
src/ubin/date/date.c
src/ubin/makefile
tools/run/bochsrc.txt

This pull request covers the following - 
1. libc wrapper for time system call
2. date utility (It returns time elapsed in seconds since Epoch - for now. We'll move it to a different implementation in future to display it in HH:MM:SS MM:DD:YYYY format)
3. Modifying Bochs VM configuration to return actual time. However, this has slowed down the system considerably. But this way we're able to get accurate results.

Date-Time Utility

---

include/nanvix/region.h
src/kernel/mm/paging.c
src/kernel/mm/region.c

With this pull, Nanvix is now able to support an arbitrary amount of memory, for this, global structure called 'miniregions' was added along with a new level of indirection to page tables.
As we discussed yesterday, the region gap size was decreased to 4MB which increases the usable size of the heap to 502MB in 512MB. The only implication is that this is the maximum number of allocatable memory at a time, limited to slightly less than 4MB, this value grows in proportion with the gap size.
I do not see a direct problem with that since this value is easily adjustable and is set in a single constant.

Miniregions implementation

---

src/kernel/arch/x86/utilities.S

Sometimes the compiler may generate code that refers to other segment registers other than CS and DS, as instructions like 'stos/stosb...', then, it is assumed that they also belong to the segment data, although, there is assurance that FS and GS are free to the user.

Using other segment registers as data segment

---

include/nanvix/syscall.h
src/kernel/sys/syscalls.c

The kernel panic on test ipc, ocurred due to a valid syscall number to wrapper functions for semaphore operations, so, the kernel tries to make a function call from a nulled function, so now, the kernel handles semop, semget and semctl as bad_syscalls and can gracefully abort the process.

Bug fix: invalid opcode exception on test ipc

---

include/nanvix/region.h
src/kernel/mm/region.c
src/kernel/sys/brk.c

As discussed in issue #67, REGION_GAP can become a problem for large memory allocations. To prevent this, was used the very size of the region as a comparison value. 
The only significant change was sys_brk, sys_brk considers that the address to be expanded/contracted will always be found within a region, which works well for region gap and the implementation before miniregion, but now, the region (in case of expansion) will always have a smaller size than new address calculated, and because of this, this address can not be contained to any region before to be expanded, and so, it is guaranteed that there will be no overlapping.
All test cases were executed and there was no problem in any of them.

Region gap is no longer needed

---

include/fs/minix.h
src/kernel/fs/block.c
tools/minix/minix.c

It was added a double indirection in the Minix file system, thus, Nanvix is now able to handle files up to 64MB instead of 519KB (7 direct blocks + 512kB of the first indirection).

Double indirection zone on Minix filesystem

---

include/ctype.h
src/lib/libc/ctype/toascii.c

According to issue #73 was removed some dependent compiler macros and distinguished standard functions from extended functions.

Aligning ctype.h to ISO C

---

.gdbinit
makefile
src/kernel/makefile
tools/build/build-img.sh
tools/dev/setup-toolchain.sh
tools/run/run-qemu.sh

This pull adds the DDD (Data Display Debugger) to the Nanvix toolchain. This debugger works as a graphical front-end for debuggers like gdb, in particular, DDD will be very helpful with the use of Qemu, since it has gdb support.
As a front-end, obviously all gdb commands are supported, but with a much greater ease of being used allied to the graphical interface that makes it possible to view structures, linked lists, functions, variables, and so on...

DDD support

---

tools/dev/setup-toolchain.sh

It is necessary to use genisoimage for creating ISO images and we can not assume that the program already exists in the system, which occurs in Ubuntu but not in Debian, for instance.
Although we assume that we are in a Debian-like environment, the program (as well as the others) are easily found in other Linux distributions so the programmer should be able to find an equivalent package.

Adding genisoimage in toolchain.

---

tools/build/build-img.sh

Update 'build-img.sh' script to detect first available loop device  instead of always trying to use /dev/loop2 :)
That's not a big change, but I think it's a good one. =)

Update 'build-img.sh' script to detect first available loop device 

---

include/nanvix/config.h
include/nanvix/debug.h
src/kernel/debug/debug.c
src/kernel/init/main.c

- Added DEBUG_MAX in config.h, representing max debugginf functions, and fixed it to 64
- Added EXTERN functions dbg_register() which added a given function in debugging table and dbg_execute() which prints and execute debugging table only if in debugging mode
- Now kmain launches dgb_execute() after all initializalisations, and this

Implementation of registerer and executer for debugging functions

---

.gitignore
include/dev/klog.h
include/dev/ramdisk.h
include/nanvix/debug.h
include/nanvix/dev.h
include/nanvix/region.h
src/kernel/debug/debug.c
src/kernel/dev/dev.c
src/kernel/dev/klog/klog.c
src/kernel/dev/ramdisk/ramdisk.c
src/kernel/mm/mm.c
src/kernel/mm/region.c
tools/dev/setup-qemu.sh

- Debug driver now prints only informations of failure
- Debug driver now raises kpanic on failure of at least one test & waits for "enter" input when all tests as successfull to continue boot.
- dbg_register now requires (debug_fn,char *) in order to be able to print function name on failure
- Modification of NR_MINIREGIONS in order to be coherent with NR_REGIONS
Simple tests implementations for:
- mm (in regions.c)
- cdev
- bdev
- klog
- rmdisk

Debug driver update & Simple tests for example

---

include/nanvix/klib.h
src/kernel/debug/debug.c
src/kernel/dev/dev.c
src/kernel/dev/klog/klog.c
src/kernel/dev/ramdisk/ramdisk.c
src/kernel/lib/kprintf.c
src/kernel/mm/region.c

Now kprintf can be called like this: kprintf([OPTIONAL: LOV_LEVEL] "[MESSAGE]",[PARAM])
With 8 possible logs levels, which can be find in klib.h
Log level has an influence only on klog and no on kout
Default log level is no log level, this is mandatory to print early boot infos in console without log_levels
Some kprintf uses it for example.

Log levels implementation for kprintf

---

.gitignore
CREDITS
include/nanvix/klib.h
src/kernel/dev/klog/klog.c
src/kernel/init/main.c
src/kernel/lib/kprintf.c

Now kprintf can be called like this: kprintf([OPTIONAL: LOV_LEVEL] "[MESSAGE]",[PARAM])
With 8 possible logs levels, which can be find in klib.h
Log levels have an influence only on klog and no on kout
Default log level is no log level, this is mandatory to print early boot infos in console without log_levels
Some kprintf in main.c uses it for example.
Also update CREDITS and .gitinore

Log levels implementation for kprintf & gitignore update

---

include/nanvix/fs.h
include/semaphore.h
include/sys/sem.h
src/kernel/fs/inode.c
src/kernel/sys/sem.c
src/kernel/sys/semclose.c
src/kernel/sys/semopen.c
src/kernel/sys/sempost.c
src/kernel/sys/semunlink.c
src/kernel/sys/semwait.c
src/lib/libc/crt0.c
src/lib/libc/sys/sem/semclose.c
src/lib/libc/sys/sem/semopen.c
src/lib/libc/sys/sem/sempost.c
src/lib/libc/sys/sem/semwait.c
src/sbin/test/test.c

- Adding sem. prefix for semaphore descriptors.
- Unlinking now makes the name available for new openings (inode is deleted from directory) -> num and dev added into ksem structure.
- User semaphore table for each process -> multiple opening on the same semaphore will result in the same address + avoids wrong address calls.
- Enhancement of test.c to test unexpected situations.

Semaphores : User table / Unlinking / Prefix / Testing

---

include/nanvix/klib.h
src/kernel/dev/klog/klog.c
src/kernel/lib/kvsprintf.c
src/kernel/sys/ps.c
tools/dev/setup-docker.sh

Useful for debug.
It's only printed when a log_level is specified. That way it's not printed in early boot console.
Whenever klog_write is called with a specified log_level, sys_gticks() is called and the result is printed
To do so, itoa() has to be swapped as a public method, now defined in klib and kvsprintf.

Printing clock ticks since initialization in kernel logs

---

.gitignore
include/nanvix/klib.h
src/kernel/dev/klog/klog.c
src/kernel/lib/kvsprintf.c
src/kernel/sys/ps.c

Useful for debug.
It's only printed when a log_level is specified. That way it's not printed in early boot console.
Whenever klog_write is called with a specified log_level, sys_gticks() is called and the result is printed
To do so, itoa() has to be swapped as a public method, now defined in klib and kvsprintf.
Also little fixes, .gitignore contained a duplicate on this branch and a log_level was printed in the boot console

Printing clock ticks since initialization in kernel logs - branch dbg-mode

---

include/nanvix/klib.h
src/kernel/dev/klog/klog.c
src/kernel/lib/kvsprintf.c
src/kernel/sys/ps.c

Useful for debug.
It's only printed when a log_level is specified. That way it's not printed in early boot console.
Whenever klog_write is called with a specified log_level, sys_gticks() is called and the result is printed
To do so, itoa() has to be swapped as a public method, now defined in klib and kvsprintf.

Printing clock ticks since initialization in kernel logs - branch master

---

.travis.yml
Dockerfile

Travis-CI implementation, working like that:
- A compiled image containing all binaries is stored on Docker hub: https://hub.docker.com/r/turbolay/nanvix/tags/
- At each push, the file .travis.yml will be triggered
- This will build the Docker Image specified in the file Docker using as base environment the first compiled image (by pulling it), which by the end tries to compile nanvix
If compilation is a success (resp. failure), travis-ci will return a success (resp. failure)
A Travis-CI account needs now to be set-up by the organisation.

First Travis-CI implementation using Docker

---

src/kernel/debug/debug.c

So log-level isn't printed anymore in early boot
Also log level for line 139 was incorrect, this is not supposed to happen and so is an error

Little fix: debug-driver initialization has now default log-level

---

.gitmodules
tools/dev/setup-toolchain.sh

This PR uses the "toolchain" repository as a submodule, this way, we can manage better the toolchain used and not have to deal with another servers, like gnu.org for instance.
Besides that, this makes the tools more integrated with the system once we have the 'Nanvix' organization, all the stuff related to Nanvix can be bind here in some way.
The submodule 'i386' points to the master branch in 'toolchain' repository, so we can pull Intel or OpenRISC toolchain only when needed.
--
Even so, there are some things that I would like to point:
* This approach works fine only if the user get the source by cloning from github, not from a zip file.
* Since we are using submodule we can't get rid the source files after installing toolchain, otherwise, git client will complaim that we have local …

Toolchain submodule

---

include/dev/8250.h
src/kernel/dev/8250/8250.c
src/kernel/dev/dev.c
src/kernel/dev/tty/console.c
src/kernel/makefile
tools/run/run-qemu.sh

This PR adds a very simple serial driver into Nanvix, it doesn't support interrupts yet (but I can push more commits adding this feature) and it's not generic enough to support OpenRISC architecture yet, since OpenRISC registers are Memory Mapped and Intel are I/O Mapped.

Support to UART 8250 and compatibles

---

include/nanvix/klib.h
src/kernel/lib/krand.c
src/kernel/lib/krand.h
src/kernel/lib/ksrand.c

Foram adicionadas à biblioteca do kernel "klib" as seguintes funções:
- krand()
- ksrand()
Ambas originadas das funções rand() e srand() da biblioteca "stdlib".

Random function added to the kernel

---

tools/dev/setup-bochs.sh
tools/dev/setup-toolchain.sh

So we can avoid problems with local invalid certificates - which happened today on a class using nanvix. :)

add flag '--no-check-certificate' to wget calls 

---

src/kernel/mm/paging.c

Since the only time that we need to change the base pointer register is when the IDLE process is creating the INIT process, we just need to check if the current process is IDLE. Therefore, this fixes #188.

i386, bug fix: when in crtpgdir(), changing EBP only when IDLE

---

src/kernel/arch/x86/utilities.S

This PR fixes #186, since the `BRTL` instruction already does the job.

i386, bug fix: no need to manually manipulate the flags

---

src/kernel/arch/x86/utilities.S

i386, bug fix: preserving registers between context switch

---

src/kernel/mm/paging.c

When a child process is created, its stack is a clone of its parent. It turns out that `PROC_KESP` points to an address relative to the parent's stack and according to the level of interrupt at that time. In the child
process, therefore, the frame pointer must point to the stack itself.
So, this PR fixes the issue #200.

bug fix, kernel stack pointer gets corrupted on fork

---

src/kernel/lib/kpanic.c
src/lib/libc/stdlib/unsetenv.c
src/ubin/nim/nim.c
tools/dev/setup-toolchain.sh

Update the compiler used in the toolchain.
Good compiler features are missing from gcc 5.8. It can help to write better C. And since the project does not use the libc there should be no major problems on doing the upgrade.
It changes some misleading indentations.
Fixes #198.

Add gcc eight support.

---

include/nanvix/syscall.h
src/kernel/sys/semopen.c

The kernel shouldn't use var_args between syscall entry-point and the handler, because it's highly arch dependent, furthermore, the kernel only accepts 4 registers as syscall parameters, so var_args doesn't make sense here. This PR solves the issue #222.

or1k, bug fix: issue #222, cannot create semaphores

---

tools/dev/arch/setup-toolchain-i386.sh
tools/dev/arch/setup-toolchain-or1k.sh

Regarding the issue #220 
Related bug issue : [https://sourceware.org/bugzilla/show_bug.cgi?id=21104](url)
Fix : avoid the usage of guile for gdb in our toolchains (flag passed to configure script)

Fix gdb building error

---

src/lib/makefile
src/sbin/makefile
src/ubin/makefile

Regarding issue #213.
Only adding **libm** to the makefile target and adding **lm** to the linker was needed. The port was already done.

libm added to sbin and ubin build

---

src/kernel/dev/dev.c

**Changes**
* `dev.c`: Modified file to set *curr_proc->errno* properly in every moment that an error is found.

Fixed missing curr_proc->errno updates at dev.c file.

---

tools/dev/setup-qemu.sh
tools/dev/setup-toolchain.sh

**Changes**
- Modified `<setup-toolchain.sh>` and `<setup-qemu.sh>` to work properly on both debian-based or arch-based systems.
- Updated qemu version.

Setup arch linux

---

tools/dev/setup-bochs.sh
tools/dev/setup-toolchain.sh

Hey. 
As I'm now an Arch user (well..Antergos, but it's based on Arch anyway)...I wanted to add support to run Nanvix on arch-based distros... and so I ported #248 from the `dev` branch to the `master` branch.
Please note that all the Ubuntu/Debian code is the same, and I adapted the code that runs on Arch to maintain the same order of the packages, so it's easier to maintain.
By the way, this is a feature commonly requested by students because a few students seem to prefer Arch, so this PR fixes that problem too.. and according to my tests everything runs fine even after this PR (well, at least on the Arch side)
Thank you!

Add support for Arch on setup-toolchain and setup-bochs scripts

---

README.md
include/sys/stat.h
makefile
tools/build/build-img.sh
tools/build/build-tools.sh
tools/dev/setup-toolchain.sh
tools/minix/makefile

This allows building the educational version of Nanvix on macOS.
The main changes concern the `build-img.sh` script, as it intensively uses standard tools (`strip`, `sed`, ...) coming from either the `binutils` package or the OS itself, that macOS also provides, but with little differences that prevent from using them "as is" (macOS inherited a bunch of UNIX tools from BSD).
The workaround is to install standard (GNU/UNIX) versions of these tools using `brew`, and refer to these standard versions in the `build-img.sh` script.
Also note that, unlike the usual build procedure for Nanvix, the macOS build flow does not compile `binutils`, `gcc` and `bochs` from source, but take the standard `brew` packages instead. This eases the building procedure a lot, but prevent from connecting `gdb` to …

Update the Build Procedure to Support macOS Hosts

---

README.md
include/nanvix/pm.h
include/unistd.h
src/kernel/makefile
src/lib/libc/unistd/alarm.c
src/lib/libc/unistd/sleep.c
src/ubin/makefile
src/ubin/sleep/sleep.c
tools/run/bochsrc.txt.tpl
tools/run/run.sh

This PR is an expansion to nanvix's libc and bosch configuration
scheme (mainly to bochs run script). Altough it includes a user
binary (namely, sleep), it merely serves the purpose of ilustrate
sleep's functionallity and shouldn't be included in default user
software-package. The following sections describe what has been
changed by this PR in detail.
Please note that if you're seeing this then the commit is still
a WIP (Work In Progress). Please refer to the Pull Request thread
for up-to-date discussion on changes proposed here.
* Changes to libc:
This changes were the inital objective of the PR, however, as
explained in [bochs configuration], the need for a more versatile
run-script was also found.
- alarm.c (new):
This file represents libc's wrapper to the sys_alarm syscall
as …

C Library Support for sleep() ad alarm()

---

tools/run/bochsrc.txt.tpl
tools/run/run.sh

In this commit, I changed the way we configure bochs in tools/run/run.sh. Instead of using sed, which has several implementations and some of them do not allow -i option, I now add some config lines directly in tools/run/bochsrc.txt using echo in tools/run/run.sh. This solution will work on any version of MacOS and Linux.

A secure way of configuring bochs in tool/runs/run.sh (works on any version of MacOS and Linux)

---

src/ubin/chown/chown.c

While trying to understand a bit more about how the `chown` utility works, I realized that it was using the `chmod` word in its usage message rather than the `chown` one - probably due a classic copy n' paste. :yum: 
My commit also removes a lot of empty spaces, but that happened due my personal editor configs. I left the removals in case you guys find it useful, but I can revert them if needed to keep the commit as straightforward / clean as possible.
And **thank you very much** for this awesome project. It has been helping me **a lot** to understand how operating systems work, alongside some books.

fix(ubin): rename wrong "chmod" from "chown" utility's usage message

---

src/kernel/pm/sched.c

This change prevents any unneeded context switch by checking if the current process is equal to next.

Add Check Before Switching to New Process

---

tools/dev/setup-bochs.sh
tools/dev/setup-toolchain.sh

This allows to run Nanvix setup scripts (`toolchain` and `bochs`) on **Manjaro**. As an arch-based distribuition that uses pacman, it's possible to support

Supporting Manjaro

---

tools/dev/setup-bochs.sh
tools/dev/setup-toolchain.sh

Some shells like zsh do not support the `${DIST,,}` directive used in the setup script. By adding the shebang at the top of the scripts, it specifies that they will only be executed by bash.
Instead of running `sudo bash tools/dev/setup-toolchain.sh`, we can simply use `sudo ./tools/dev/setup-toolchain.sh`

Add bash shebang to run setup scripts with others shells

---

tools/dev/setup/arch.sh

This is a script for Arch Linux distribution.
It upgrade all Pacman packages and install the required packages to compile the tools and run Nanvix.
The script was tested on Arch and Manjaro 23.1.0 Vulcan.

Script for Arch Linux distribution
